/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix.impl;

import edu.upb.lp.isc.perronix.DoubleExpression;
import edu.upb.lp.isc.perronix.PerronixPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Double Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DoubleExpressionImpl extends PrintExpressionImpl implements DoubleExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DoubleExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerronixPackage.Literals.DOUBLE_EXPRESSION;
  }

} //DoubleExpressionImpl
