/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix.impl;

import edu.upb.lp.isc.perronix.ListTail;
import edu.upb.lp.isc.perronix.PerronixPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>List Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ListTailImpl extends ExpressionImpl implements ListTail
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListTailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerronixPackage.Literals.LIST_TAIL;
  }

} //ListTailImpl
