/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix.impl;

import edu.upb.lp.isc.perronix.Define;
import edu.upb.lp.isc.perronix.Expression;
import edu.upb.lp.isc.perronix.MyRacketProgram;
import edu.upb.lp.isc.perronix.PerronixPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>My Racket Program</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.perronix.impl.MyRacketProgramImpl#getDefines <em>Defines</em>}</li>
 *   <li>{@link edu.upb.lp.isc.perronix.impl.MyRacketProgramImpl#getExecutions <em>Executions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MyRacketProgramImpl extends MinimalEObjectImpl.Container implements MyRacketProgram
{
  /**
   * The cached value of the '{@link #getDefines() <em>Defines</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefines()
   * @generated
   * @ordered
   */
  protected EList<Define> defines;

  /**
   * The cached value of the '{@link #getExecutions() <em>Executions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExecutions()
   * @generated
   * @ordered
   */
  protected EList<Expression> executions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MyRacketProgramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PerronixPackage.Literals.MY_RACKET_PROGRAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Define> getDefines()
  {
    if (defines == null)
    {
      defines = new EObjectContainmentEList<Define>(Define.class, this, PerronixPackage.MY_RACKET_PROGRAM__DEFINES);
    }
    return defines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expression> getExecutions()
  {
    if (executions == null)
    {
      executions = new EObjectContainmentEList<Expression>(Expression.class, this, PerronixPackage.MY_RACKET_PROGRAM__EXECUTIONS);
    }
    return executions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PerronixPackage.MY_RACKET_PROGRAM__DEFINES:
        return ((InternalEList<?>)getDefines()).basicRemove(otherEnd, msgs);
      case PerronixPackage.MY_RACKET_PROGRAM__EXECUTIONS:
        return ((InternalEList<?>)getExecutions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PerronixPackage.MY_RACKET_PROGRAM__DEFINES:
        return getDefines();
      case PerronixPackage.MY_RACKET_PROGRAM__EXECUTIONS:
        return getExecutions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PerronixPackage.MY_RACKET_PROGRAM__DEFINES:
        getDefines().clear();
        getDefines().addAll((Collection<? extends Define>)newValue);
        return;
      case PerronixPackage.MY_RACKET_PROGRAM__EXECUTIONS:
        getExecutions().clear();
        getExecutions().addAll((Collection<? extends Expression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PerronixPackage.MY_RACKET_PROGRAM__DEFINES:
        getDefines().clear();
        return;
      case PerronixPackage.MY_RACKET_PROGRAM__EXECUTIONS:
        getExecutions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PerronixPackage.MY_RACKET_PROGRAM__DEFINES:
        return defines != null && !defines.isEmpty();
      case PerronixPackage.MY_RACKET_PROGRAM__EXECUTIONS:
        return executions != null && !executions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MyRacketProgramImpl
