/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import perronix.ui.internal.PerronixActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PerronixExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PerronixActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PerronixActivator activator = PerronixActivator.getInstance();
		return activator != null ? activator.getInjector(PerronixActivator.EDU_UPB_LP_ISC_PERRONIX) : null;
	}

}
