/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.parser.antlr;

import com.google.inject.Inject;
import edu.upb.lp.isc.parser.antlr.internal.InternalPerronixParser;
import edu.upb.lp.isc.services.PerronixGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PerronixParser extends AbstractAntlrParser {

	@Inject
	private PerronixGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPerronixParser createParser(XtextTokenStream stream) {
		return new InternalPerronixParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MyRacketProgram";
	}

	public PerronixGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PerronixGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
