/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Double Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getDoubleExpression()
 * @model
 * @generated
 */
public interface DoubleExpression extends PrintExpression
{
} // DoubleExpression
