/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
