/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Length List</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getLengthList()
 * @model
 * @generated
 */
public interface LengthList extends Expression
{
} // LengthList
