/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Double</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.perronix.ListDouble#getT <em>T</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getListDouble()
 * @model
 * @generated
 */
public interface ListDouble extends Expression
{
  /**
   * Returns the value of the '<em><b>T</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.perronix.DoubleExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' containment reference list.
   * @see edu.upb.lp.isc.perronix.PerronixPackage#getListDouble_T()
   * @model containment="true"
   * @generated
   */
  EList<DoubleExpression> getT();

} // ListDouble
