/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.perronix.ListInt#getS <em>S</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getListInt()
 * @model
 * @generated
 */
public interface ListInt extends Expression, LengthList, ListTail
{
  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.perronix.IntExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference list.
   * @see edu.upb.lp.isc.perronix.PerronixPackage#getListInt_S()
   * @model containment="true"
   * @generated
   */
  EList<IntExpression> getS();

} // ListInt
