/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getListTail()
 * @model
 * @generated
 */
public interface ListTail extends Expression
{
} // ListTail
