/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.perronix.PerronixFactory
 * @model kind="package"
 * @generated
 */
public interface PerronixPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "perronix";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/isc/Perronix";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "perronix";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PerronixPackage eINSTANCE = edu.upb.lp.isc.perronix.impl.PerronixPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.MyRacketProgramImpl <em>My Racket Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.MyRacketProgramImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getMyRacketProgram()
   * @generated
   */
  int MY_RACKET_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Defines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM__DEFINES = 0;

  /**
   * The feature id for the '<em><b>Executions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM__EXECUTIONS = 1;

  /**
   * The number of structural features of the '<em>My Racket Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.DefineImpl <em>Define</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.DefineImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getDefine()
   * @generated
   */
  int DEFINE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__BODY = 2;

  /**
   * The number of structural features of the '<em>Define</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.ExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.SimpleExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getSimpleExpression()
   * @generated
   */
  int SIMPLE_EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>Simple Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.PrintExpressionImpl <em>Print Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.PrintExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getPrintExpression()
   * @generated
   */
  int PRINT_EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_EXPRESSION__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.IntExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION__VALUE = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.DoubleExpressionImpl <em>Double Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.DoubleExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getDoubleExpression()
   * @generated
   */
  int DOUBLE_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_EXPRESSION__VALUE = PRINT_EXPRESSION__VALUE;

  /**
   * The number of structural features of the '<em>Double Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_EXPRESSION_FEATURE_COUNT = PRINT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.StringExpressionImpl <em>String Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.StringExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getStringExpression()
   * @generated
   */
  int STRING_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EXPRESSION__VALUE = 0;

  /**
   * The number of structural features of the '<em>String Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.ArithExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getArithExpression()
   * @generated
   */
  int ARITH_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__OP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__ARGS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Arith Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.IfExpressionImpl <em>If Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.IfExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getIfExpression()
   * @generated
   */
  int IF_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__COND = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__THEN = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__ELSE = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.FunctionCallExpressionImpl <em>Function Call Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.FunctionCallExpressionImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getFunctionCallExpression()
   * @generated
   */
  int FUNCTION_CALL_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION__FUNCTION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION__ARGS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function Call Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.ListIntImpl <em>List Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.ListIntImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListInt()
   * @generated
   */
  int LIST_INT = 11;

  /**
   * The feature id for the '<em><b>S</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_INT__S = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_INT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.ListDoubleImpl <em>List Double</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.ListDoubleImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListDouble()
   * @generated
   */
  int LIST_DOUBLE = 12;

  /**
   * The feature id for the '<em><b>T</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_DOUBLE__T = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Double</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_DOUBLE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.ListStringImpl <em>List String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.ListStringImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListString()
   * @generated
   */
  int LIST_STRING = 13;

  /**
   * The feature id for the '<em><b>T</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_STRING__T = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_STRING_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.LengthListImpl <em>Length List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.LengthListImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getLengthList()
   * @generated
   */
  int LENGTH_LIST = 14;

  /**
   * The number of structural features of the '<em>Length List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_LIST_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.ListTailImpl <em>List Tail</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.ListTailImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListTail()
   * @generated
   */
  int LIST_TAIL = 15;

  /**
   * The number of structural features of the '<em>List Tail</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_TAIL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.perronix.impl.WhileLoopImpl <em>While Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.perronix.impl.WhileLoopImpl
   * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getWhileLoop()
   * @generated
   */
  int WHILE_LOOP = 16;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_LOOP__FUNCTION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_LOOP__ARGS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_LOOP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.MyRacketProgram <em>My Racket Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My Racket Program</em>'.
   * @see edu.upb.lp.isc.perronix.MyRacketProgram
   * @generated
   */
  EClass getMyRacketProgram();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.perronix.MyRacketProgram#getDefines <em>Defines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Defines</em>'.
   * @see edu.upb.lp.isc.perronix.MyRacketProgram#getDefines()
   * @see #getMyRacketProgram()
   * @generated
   */
  EReference getMyRacketProgram_Defines();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.perronix.MyRacketProgram#getExecutions <em>Executions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Executions</em>'.
   * @see edu.upb.lp.isc.perronix.MyRacketProgram#getExecutions()
   * @see #getMyRacketProgram()
   * @generated
   */
  EReference getMyRacketProgram_Executions();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.Define <em>Define</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Define</em>'.
   * @see edu.upb.lp.isc.perronix.Define
   * @generated
   */
  EClass getDefine();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.perronix.Define#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.perronix.Define#getName()
   * @see #getDefine()
   * @generated
   */
  EAttribute getDefine_Name();

  /**
   * Returns the meta object for the attribute list '{@link edu.upb.lp.isc.perronix.Define#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see edu.upb.lp.isc.perronix.Define#getParams()
   * @see #getDefine()
   * @generated
   */
  EAttribute getDefine_Params();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.perronix.Define#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see edu.upb.lp.isc.perronix.Define#getBody()
   * @see #getDefine()
   * @generated
   */
  EReference getDefine_Body();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see edu.upb.lp.isc.perronix.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.SimpleExpression <em>Simple Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Expression</em>'.
   * @see edu.upb.lp.isc.perronix.SimpleExpression
   * @generated
   */
  EClass getSimpleExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.PrintExpression <em>Print Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print Expression</em>'.
   * @see edu.upb.lp.isc.perronix.PrintExpression
   * @generated
   */
  EClass getPrintExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.perronix.PrintExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.perronix.PrintExpression#getValue()
   * @see #getPrintExpression()
   * @generated
   */
  EAttribute getPrintExpression_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see edu.upb.lp.isc.perronix.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.perronix.IntExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.perronix.IntExpression#getValue()
   * @see #getIntExpression()
   * @generated
   */
  EAttribute getIntExpression_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.DoubleExpression <em>Double Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Expression</em>'.
   * @see edu.upb.lp.isc.perronix.DoubleExpression
   * @generated
   */
  EClass getDoubleExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.StringExpression <em>String Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Expression</em>'.
   * @see edu.upb.lp.isc.perronix.StringExpression
   * @generated
   */
  EClass getStringExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.perronix.StringExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.perronix.StringExpression#getValue()
   * @see #getStringExpression()
   * @generated
   */
  EAttribute getStringExpression_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.ArithExpression <em>Arith Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Expression</em>'.
   * @see edu.upb.lp.isc.perronix.ArithExpression
   * @generated
   */
  EClass getArithExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.perronix.ArithExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.perronix.ArithExpression#getOp()
   * @see #getArithExpression()
   * @generated
   */
  EAttribute getArithExpression_Op();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.perronix.ArithExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.perronix.ArithExpression#getArgs()
   * @see #getArithExpression()
   * @generated
   */
  EReference getArithExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.IfExpression <em>If Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Expression</em>'.
   * @see edu.upb.lp.isc.perronix.IfExpression
   * @generated
   */
  EClass getIfExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.perronix.IfExpression#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see edu.upb.lp.isc.perronix.IfExpression#getCond()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Cond();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.perronix.IfExpression#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see edu.upb.lp.isc.perronix.IfExpression#getThen()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Then();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.perronix.IfExpression#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else</em>'.
   * @see edu.upb.lp.isc.perronix.IfExpression#getElse()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Else();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.FunctionCallExpression <em>Function Call Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call Expression</em>'.
   * @see edu.upb.lp.isc.perronix.FunctionCallExpression
   * @generated
   */
  EClass getFunctionCallExpression();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.perronix.FunctionCallExpression#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see edu.upb.lp.isc.perronix.FunctionCallExpression#getFunction()
   * @see #getFunctionCallExpression()
   * @generated
   */
  EReference getFunctionCallExpression_Function();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.perronix.FunctionCallExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see edu.upb.lp.isc.perronix.FunctionCallExpression#getArgs()
   * @see #getFunctionCallExpression()
   * @generated
   */
  EReference getFunctionCallExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.ListInt <em>List Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Int</em>'.
   * @see edu.upb.lp.isc.perronix.ListInt
   * @generated
   */
  EClass getListInt();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.perronix.ListInt#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>S</em>'.
   * @see edu.upb.lp.isc.perronix.ListInt#getS()
   * @see #getListInt()
   * @generated
   */
  EReference getListInt_S();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.ListDouble <em>List Double</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Double</em>'.
   * @see edu.upb.lp.isc.perronix.ListDouble
   * @generated
   */
  EClass getListDouble();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.perronix.ListDouble#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>T</em>'.
   * @see edu.upb.lp.isc.perronix.ListDouble#getT()
   * @see #getListDouble()
   * @generated
   */
  EReference getListDouble_T();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.ListString <em>List String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List String</em>'.
   * @see edu.upb.lp.isc.perronix.ListString
   * @generated
   */
  EClass getListString();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.perronix.ListString#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>T</em>'.
   * @see edu.upb.lp.isc.perronix.ListString#getT()
   * @see #getListString()
   * @generated
   */
  EReference getListString_T();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.LengthList <em>Length List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Length List</em>'.
   * @see edu.upb.lp.isc.perronix.LengthList
   * @generated
   */
  EClass getLengthList();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.ListTail <em>List Tail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Tail</em>'.
   * @see edu.upb.lp.isc.perronix.ListTail
   * @generated
   */
  EClass getListTail();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.perronix.WhileLoop <em>While Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Loop</em>'.
   * @see edu.upb.lp.isc.perronix.WhileLoop
   * @generated
   */
  EClass getWhileLoop();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.perronix.WhileLoop#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see edu.upb.lp.isc.perronix.WhileLoop#getFunction()
   * @see #getWhileLoop()
   * @generated
   */
  EReference getWhileLoop_Function();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.perronix.WhileLoop#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see edu.upb.lp.isc.perronix.WhileLoop#getArgs()
   * @see #getWhileLoop()
   * @generated
   */
  EReference getWhileLoop_Args();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PerronixFactory getPerronixFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.MyRacketProgramImpl <em>My Racket Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.MyRacketProgramImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getMyRacketProgram()
     * @generated
     */
    EClass MY_RACKET_PROGRAM = eINSTANCE.getMyRacketProgram();

    /**
     * The meta object literal for the '<em><b>Defines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_RACKET_PROGRAM__DEFINES = eINSTANCE.getMyRacketProgram_Defines();

    /**
     * The meta object literal for the '<em><b>Executions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_RACKET_PROGRAM__EXECUTIONS = eINSTANCE.getMyRacketProgram_Executions();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.DefineImpl <em>Define</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.DefineImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getDefine()
     * @generated
     */
    EClass DEFINE = eINSTANCE.getDefine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINE__NAME = eINSTANCE.getDefine_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINE__PARAMS = eINSTANCE.getDefine_Params();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINE__BODY = eINSTANCE.getDefine_Body();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.ExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.SimpleExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getSimpleExpression()
     * @generated
     */
    EClass SIMPLE_EXPRESSION = eINSTANCE.getSimpleExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.PrintExpressionImpl <em>Print Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.PrintExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getPrintExpression()
     * @generated
     */
    EClass PRINT_EXPRESSION = eINSTANCE.getPrintExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRINT_EXPRESSION__VALUE = eINSTANCE.getPrintExpression_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.IntExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_EXPRESSION__VALUE = eINSTANCE.getIntExpression_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.DoubleExpressionImpl <em>Double Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.DoubleExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getDoubleExpression()
     * @generated
     */
    EClass DOUBLE_EXPRESSION = eINSTANCE.getDoubleExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.StringExpressionImpl <em>String Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.StringExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getStringExpression()
     * @generated
     */
    EClass STRING_EXPRESSION = eINSTANCE.getStringExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_EXPRESSION__VALUE = eINSTANCE.getStringExpression_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.ArithExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getArithExpression()
     * @generated
     */
    EClass ARITH_EXPRESSION = eINSTANCE.getArithExpression();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARITH_EXPRESSION__OP = eINSTANCE.getArithExpression_Op();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_EXPRESSION__ARGS = eINSTANCE.getArithExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.IfExpressionImpl <em>If Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.IfExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getIfExpression()
     * @generated
     */
    EClass IF_EXPRESSION = eINSTANCE.getIfExpression();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__COND = eINSTANCE.getIfExpression_Cond();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__THEN = eINSTANCE.getIfExpression_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__ELSE = eINSTANCE.getIfExpression_Else();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.FunctionCallExpressionImpl <em>Function Call Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.FunctionCallExpressionImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getFunctionCallExpression()
     * @generated
     */
    EClass FUNCTION_CALL_EXPRESSION = eINSTANCE.getFunctionCallExpression();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL_EXPRESSION__FUNCTION = eINSTANCE.getFunctionCallExpression_Function();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL_EXPRESSION__ARGS = eINSTANCE.getFunctionCallExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.ListIntImpl <em>List Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.ListIntImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListInt()
     * @generated
     */
    EClass LIST_INT = eINSTANCE.getListInt();

    /**
     * The meta object literal for the '<em><b>S</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_INT__S = eINSTANCE.getListInt_S();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.ListDoubleImpl <em>List Double</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.ListDoubleImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListDouble()
     * @generated
     */
    EClass LIST_DOUBLE = eINSTANCE.getListDouble();

    /**
     * The meta object literal for the '<em><b>T</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_DOUBLE__T = eINSTANCE.getListDouble_T();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.ListStringImpl <em>List String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.ListStringImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListString()
     * @generated
     */
    EClass LIST_STRING = eINSTANCE.getListString();

    /**
     * The meta object literal for the '<em><b>T</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_STRING__T = eINSTANCE.getListString_T();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.LengthListImpl <em>Length List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.LengthListImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getLengthList()
     * @generated
     */
    EClass LENGTH_LIST = eINSTANCE.getLengthList();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.ListTailImpl <em>List Tail</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.ListTailImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getListTail()
     * @generated
     */
    EClass LIST_TAIL = eINSTANCE.getListTail();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.perronix.impl.WhileLoopImpl <em>While Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.perronix.impl.WhileLoopImpl
     * @see edu.upb.lp.isc.perronix.impl.PerronixPackageImpl#getWhileLoop()
     * @generated
     */
    EClass WHILE_LOOP = eINSTANCE.getWhileLoop();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_LOOP__FUNCTION = eINSTANCE.getWhileLoop_Function();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_LOOP__ARGS = eINSTANCE.getWhileLoop_Args();

  }

} //PerronixPackage
