/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getSimpleExpression()
 * @model
 * @generated
 */
public interface SimpleExpression extends Expression
{
} // SimpleExpression
