/**
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.perronix;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.perronix.WhileLoop#getFunction <em>Function</em>}</li>
 *   <li>{@link edu.upb.lp.isc.perronix.WhileLoop#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.perronix.PerronixPackage#getWhileLoop()
 * @model
 * @generated
 */
public interface WhileLoop extends Expression
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' reference.
   * @see #setFunction(Define)
   * @see edu.upb.lp.isc.perronix.PerronixPackage#getWhileLoop_Function()
   * @model
   * @generated
   */
  Define getFunction();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.perronix.WhileLoop#getFunction <em>Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(Define value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(Expression)
   * @see edu.upb.lp.isc.perronix.PerronixPackage#getWhileLoop_Args()
   * @model containment="true"
   * @generated
   */
  Expression getArgs();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.perronix.WhileLoop#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(Expression value);

} // WhileLoop
