/*
 * generated by Xtext 2.21.0
 */
package edu.upb.lp.isc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.upb.lp.isc.PerronixRuntimeModule;
import edu.upb.lp.isc.PerronixStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PerronixIdeSetup extends PerronixStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PerronixRuntimeModule(), new PerronixIdeModule()));
	}
	
}
